<a href="https://colab.research.google.com/github/leman-cap13/phobia-quiz-/blob/main/CustomerSegmentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
! kaggle  datasets download kaushiksuresh147/customer-segmentation

Dataset URL: https://www.kaggle.com/datasets/kaushiksuresh147/customer-segmentation
License(s): CC0-1.0
customer-segmentation.zip: Skipping, found more recently modified local copy (use --force to force download)


In [ ]:
!unzip /content/customer-segmentation.zip

Archive:  /content/customer-segmentation.zip
replace Test.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: no
replace Train.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: yes
  inflating: Train.csv               


In [ ]:
df=pd.read_csv('/content/Train.csv')
df

ID  Gender Ever_Married  Age Graduated     Profession  \
0     462809    Male           No   22        No     Healthcare   
1     462643  Female          Yes   38       Yes       Engineer   
2     466315  Female          Yes   67       Yes       Engineer   
3     461735    Male          Yes   67       Yes         Lawyer   
4     462669  Female          Yes   40       Yes  Entertainment   
...      ...     ...          ...  ...       ...            ...   
8063  464018    Male           No   22        No            NaN   
8064  464685    Male           No   35        No      Executive   
8065  465406  Female           No   33       Yes     Healthcare   
8066  467299  Female           No   27       Yes     Healthcare   
8067  461879    Male          Yes   37       Yes      Executive   

      Work_Experience Spending_Score  Family_Size  Var_1 Segmentation  
0                 1.0            Low          4.0  Cat_4            D  
1                 NaN        Average          3.0  Cat_4            A  
2                 1.0            Low          1.0  Cat_6            B  
3                 0.0           High          2.0  Cat_6            B  
4                 NaN           High          6.0  Cat_6            A  
...               ...            ...          ...    ...          ...  
8063              0.0            Low          7.0  Cat_1            D  
8064              3.0            Low          4.0  Cat_4            D  
8065              1.0            Low          1.0  Cat_6            D  
8066              1.0            Low          4.0  Cat_6            B  
8067              0.0        Average          3.0  Cat_4            B  

[8068 rows x 11 columns]

In [ ]:
df.loc[:,'Profession']=df['Profession'].fillna('Unknown')
df['Profession'].isna().sum()

0

In [ ]:
df.loc[:,'Family_Size']=df['Family_Size'].fillna(df['Family_Size'].mean())
df['Family_Size'].isna().sum()

0

In [ ]:
df.loc[:,'Work_Experience']=df['Work_Experience'].fillna(df['Work_Experience'].median())
df['Work_Experience']

0       1.0
1       1.0
2       1.0
3       0.0
4       1.0
       ... 
8063    0.0
8064    3.0
8065    1.0
8066    1.0
8067    0.0
Name: Work_Experience, Length: 8068, dtype: float64

In [ ]:
df['Work_Experience'].isna().sum()

0

In [ ]:
df['Var_1']=df['Var_1'].str.replace('_', ' ', regex=True)
# df['Var_1'].str.replace(r'([a-zA-Z])(\d)', r'\1 \2', regex=True)


In [ ]:
df.loc[:,'Var_1']=df['Var_1'].fillna('missing_value')
df['Var_1'].isna().sum()

0

In [ ]:
df.isna().sum()

ID                   0
Gender               0
Ever_Married       140
Age                  0
Graduated           78
Profession           0
Work_Experience      0
Spending_Score       0
Family_Size          0
Var_1                0
Segmentation         0
dtype: int64

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.dtypes

ID                   int64
Gender              object
Ever_Married        object
Age                  int64
Graduated           object
Profession          object
Work_Experience    float64
Spending_Score      object
Family_Size        float64
Var_1               object
Segmentation        object
dtype: object

In [ ]:
df.columns

Index(['ID', 'Gender', 'Ever_Married', 'Age', 'Graduated', 'Profession',
       'Work_Experience', 'Spending_Score', 'Family_Size', 'Var_1',
       'Segmentation'],
      dtype='object')

In [ ]:
df=df.drop(['Graduated','Ever_Married'],axis=1)
df

ID  Gender  Age     Profession  Work_Experience Spending_Score  \
0     462809    Male   22     Healthcare              1.0            Low   
1     462643  Female   38       Engineer              1.0        Average   
2     466315  Female   67       Engineer              1.0            Low   
3     461735    Male   67         Lawyer              0.0           High   
4     462669  Female   40  Entertainment              1.0           High   
...      ...     ...  ...            ...              ...            ...   
8063  464018    Male   22        Unknown              0.0            Low   
8064  464685    Male   35      Executive              3.0            Low   
8065  465406  Female   33     Healthcare              1.0            Low   
8066  467299  Female   27     Healthcare              1.0            Low   
8067  461879    Male   37      Executive              0.0        Average   

      Family_Size  Var_1 Segmentation  
0             4.0  Cat 4            D  
1             3.0  Cat 4            A  
2             1.0  Cat 6            B  
3             2.0  Cat 6            B  
4             6.0  Cat 6            A  
...           ...    ...          ...  
8063          7.0  Cat 1            D  
8064          4.0  Cat 4            D  
8065          1.0  Cat 6            D  
8066          4.0  Cat 6            B  
8067          3.0  Cat 4            B  

[8068 rows x 9 columns]

In [ ]:
df['Segmentation'].nunique()

4

In [ ]:
Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = (df['Age'] < lower_bound) | (df['Age'] > upper_bound)
df = df[~outliers]

In [ ]:
df['Age']

0       22
1       38
2       67
3       67
4       40
        ..
8063    22
8064    35
8065    33
8066    27
8067    37
Name: Age, Length: 7809, dtype: int64

In [ ]:
Q1 = df['Work_Experience'].quantile(0.25)
Q3 = df['Work_Experience'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = (df['Work_Experience'] < lower_bound) | (df['Work_Experience'] > upper_bound)
df = df[~outliers]

In [ ]:
df['Work_Experience']

0       1.0
1       1.0
2       1.0
3       0.0
4       1.0
       ... 
8063    0.0
8064    3.0
8065    1.0
8066    1.0
8067    0.0
Name: Work_Experience, Length: 7809, dtype: float64

In [ ]:
X=df.drop('Segmentation',axis=1)
y=df['Segmentation'].copy()

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y,random_state=13)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y_train=le.fit_transform(y_train)
y_train

array([2, 0, 0, ..., 0, 1, 0])

In [ ]:
y_test=le.fit_transform(y_test)
y_test

array([1, 2, 0, ..., 3, 1, 3])

In [ ]:
num_feature=X_train.select_dtypes(include=np.number).columns
cat_feature=X_train.select_dtypes(exclude=np.number).columns

In [ ]:
cat_feature

Index(['Gender', 'Profession', 'Spending_Score', 'Var_1'], dtype='object')

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

In [ ]:
num_pipeline =Pipeline([
    ('impute',SimpleImputer(strategy='median')),
    ('encoder',StandardScaler())
])

cat_pipeline=Pipeline([
    ('impute',SimpleImputer(strategy='constant',fill_value='missing')),
    ('encoder',OneHotEncoder(handle_unknown='ignore',sparse_output=False))
])

transformer=ColumnTransformer([
    ('num',num_pipeline,num_feature),
    ('cat',cat_pipeline,cat_feature)
],remainder='passthrough')

estimator=RandomForestClassifier()

full_pipeline=Pipeline([
    ('preprocessing',transformer),
    ('estimator',estimator)
])

In [ ]:
full_pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('encoder',
                                                                   StandardScaler())]),
                                                  Index(['ID', 'Age', 'Work_Experience', 'Family_Size'], dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  Index(['Gender', 'Profession', 'Spending_Score', 'Var_1'], dtype='object'))])),
                ('estimator', RandomForestClassifier())])

In [ ]:
full_pipeline.score(X_test,y_test)

0.5057618437900128

In [ ]:
X_train_prepared=pd.DataFrame(transformer.fit_transform(X_train),columns=transformer.get_feature_names_out())
X_test_prepared=pd.DataFrame(transformer.transform(X_test),columns=transformer.get_feature_names_out())

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(X_train_prepared,y_train)
rfc.score(X_test_prepared,y_test)

0.5038412291933418

In [ ]:
sorted(zip(rfc.feature_importances_,X_train_prepared.columns))

[(0.0029347076590945224, 'cat__Var_1_Cat 5'),
 (0.0032992061588253503, 'cat__Var_1_missing_value'),
 (0.004434562745748643, 'cat__Profession_Unknown'),
 (0.004566418361185433, 'cat__Var_1_Cat 1'),
 (0.005642753077010579, 'cat__Profession_Lawyer'),
 (0.005690835787895725, 'cat__Profession_Homemaker'),
 (0.005749187459006916, 'cat__Var_1_Cat 7'),
 (0.007652194622602152, 'cat__Profession_Executive'),
 (0.008016887871590756, 'cat__Spending_Score_High'),
 (0.0083350936790783, 'cat__Profession_Marketing'),
 (0.008504648203343774, 'cat__Var_1_Cat 2'),
 (0.010233742991421917, 'cat__Profession_Engineer'),
 (0.010341334995755297, 'cat__Profession_Doctor'),
 (0.011982636657364692, 'cat__Var_1_Cat 3'),
 (0.012382081187861934, 'cat__Profession_Entertainment'),
 (0.014353865665975093, 'cat__Var_1_Cat 4'),
 (0.014927845512436524, 'cat__Gender_Male'),
 (0.015448871598500141, 'cat__Gender_Female'),
 (0.017809805018057363, 'cat__Var_1_Cat 6'),
 (0.020173350489478412, 'cat__Spending_Score_Average'),
 (0.

In [ ]:
df.columns

Index(['ID', 'Gender', 'Age', 'Profession', 'Work_Experience',
       'Spending_Score', 'Family_Size', 'Var_1', 'Segmentation'],
      dtype='object')

In [ ]:
from sklearn.model_selection import GridSearchCV
params={
        'estimator__n_estimators':[90,93,95],
        'estimator__max_features':[3,5,7]
}

gscv=GridSearchCV(full_pipeline,params,cv=3,scoring='neg_mean_absolute_error')
gscv.fit(X_train,y_train)

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('num',
                                                                         Pipeline(steps=[('impute',
                                                                                          SimpleImputer(strategy='median')),
                                                                                         ('encoder',
                                                                                          StandardScaler())]),
                                                                         Index(['ID', 'Age', 'Work_Experience', 'Family_Size'], dtype='object')),
                                                                        ('cat',
                                                                         Pipeline(steps=[('impute',
                                                                                          SimpleImputer(fill_value='missing',
                                                                                                        strategy='constant')),
                                                                                         ('encoder',
                                                                                          OneHotEncoder(handle_unknown='ignore',
                                                                                                        sparse_output=False))]),
                                                                         Index(['Gender', 'Profession', 'Spending_Score', 'Var_1'], dtype='object'))])),
                                       ('estimator',
                                        RandomForestClassifier())]),
             param_grid={'estimator__max_features': [3, 5, 7],
                         'estimator__n_estimators': [90, 93, 95]},
             scoring='neg_mean_absolute_error')

In [ ]:
gscv.best_params_

{'estimator__max_features': 5, 'estimator__n_estimators': 95}

In [ ]:
gscv.best_estimator_.score(X_test,y_test)

0.5057618437900128

In [ ]:
gscv.best_estimator_.predict(X_test.iloc[:5])

array([2, 2, 0, 3, 1])

In [ ]:
y_test[:5]

array([1, 2, 0, 3, 2])

In [ ]:
num_feature

Index(['ID', 'Age', 'Work_Experience', 'Family_Size'], dtype='object')

In [ ]:
df['Family_Size'].max()

9.0

In [ ]:
y.value_counts() / len(y)

Segmentation
D    0.280830
C    0.246895
A    0.240876
B    0.231400
Name: count, dtype: float64

In [ ]:
from sklearn.model_selection import cross_val_score

rf = RandomForestClassifier(n_estimators=100, random_state=13)
scores = cross_val_score(full_pipeline, X_train, y_train, cv=5, error_score='raise')

print(f"Cross-validation accuracy: {scores.mean():.4f}")

Cross-validation accuracy: 0.5071
