<a href="https://colab.research.google.com/github/leman-cap13/phobia-quiz-/blob/main/MobilePriceClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
!kaggle datasets download iabhishekofficial/mobile-price-classification

Dataset URL: https://www.kaggle.com/datasets/iabhishekofficial/mobile-price-classification
License(s): unknown
mobile-price-classification.zip: Skipping, found more recently modified local copy (use --force to force download)


In [ ]:
!unzip /content/mobile-price-classification.zip

Archive:  /content/mobile-price-classification.zip
replace test.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace train.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: train.csv               


In [ ]:
df=pd.read_csv('/content/train.csv')
df

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2   2         20       756  2549     9     7   
1       0.7        136        3   6        905      1988  2631    17     3   
2       0.9        145        5   6       1263      1716  2603    11     2   
3       0.8        131        6   9       1216      1786  2769    16     8   
4       0.6        141        2  14       1208      1212  1411     8     2   
...     ...        ...      ...  ..        ...       ...   ...   ...   ...   
1995    0.8        106        6  14       1222      1890   668    13     4   
1996    0.2        187        4   3        915      1965  2032    11    10   
1997    0.7        108        8   3        868      1632  3057     9     1   
1998    0.1        145        5   5        336       670   869    18    10   
1999    0.9        168        6  16        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [ ]:
pd.set_option('display.max_columns', None)
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2   2         20       756  2549     9     7         19   
1        136        3   6        905      1988  2631    17     3          7   
2        145        5   6       1263      1716  2603    11     2          9   
3        131        6   9       1216      1786  2769    16     8         11   
4        141        2  14       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1

In [ ]:
df.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='object')

In [ ]:
df.shape

(2000, 21)

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.dtypes

battery_power      int64
blue               int64
clock_speed      float64
dual_sim           int64
fc                 int64
four_g             int64
int_memory         int64
m_dep            float64
mobile_wt          int64
n_cores            int64
pc                 int64
px_height          int64
px_width           int64
ram                int64
sc_h               int64
sc_w               int64
talk_time          int64
three_g            int64
touch_screen       int64
wifi               int64
price_range        int64
dtype: object

In [ ]:
X=df.drop('price_range',axis=1)
y=df['price_range'].copy()

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
num_feature=X_train.select_dtypes(include=[np.number]).columns
cat_feature=X_train.select_dtypes(exclude=[np.number]).columns

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing  import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

In [ ]:
num_pipeline=Pipeline([
    ('impute', SimpleImputer(strategy='median')),
    ('scale', StandardScaler())
])

#Useless code
# cat_pipeline = Pipeline([
#     ('impute', SimpleImputer(strategy='constant',fill_value='missing')),
#     ('onehotencoder',OneHotEncoder(handle_unknown='ignore',sparse_output='ignore'))
# ])

transformer=ColumnTransformer([
    ('num',num_pipeline, num_feature)
    # ('cat',cat_pipeline,cat_feature)
],remainder='passthrough')

estimator= RandomForestClassifier()

full_pipeline =Pipeline([
    ('preprocessing', transformer),
    ('estimator',estimator)
])

In [ ]:
full_pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi'],
      dtype='object'))])),
                ('estimator', RandomForestClassifier())])

In [ ]:
full_pipeline.score(X_test, y_test)

0.875

In [ ]:
full_pipeline.predict(X_test.iloc[:10])

array([0, 1, 1, 0, 2, 1, 0, 2, 2, 3])

In [ ]:
y_test.iloc[:10]

674     0
1699    0
1282    1
1315    1
1210    2
1636    2
613     0
447     2
1131    2
808     3
Name: price_range, dtype: int64

In [ ]:
X_train_prepared=pd.DataFrame(transformer.fit_transform(X_train),columns=transformer.get_feature_names_out())
X_test_prepared=pd.DataFrame(transformer.transform(X_test),columns=transformer.get_feature_names_out())

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rfc = RandomForestClassifier()

rfc.fit(X_train_prepared, y_train)
rfc.score(X_test_prepared, y_test)

0.8675

In [ ]:
sorted(zip(rfc.feature_importances_, X_train_prepared.columns))



[(0.005416248054685431, 'num__three_g'),
 (0.006492713574153412, 'num__wifi'),
 (0.006931333702594852, 'num__blue'),
 (0.006934975618629029, 'num__touch_screen'),
 (0.007152077665643795, 'num__dual_sim'),
 (0.00722763323700999, 'num__four_g'),
 (0.023608778034537415, 'num__n_cores'),
 (0.02478234202215913, 'num__m_dep'),
 (0.026299757938401277, 'num__fc'),
 (0.027152529887087443, 'num__sc_h'),
 (0.027567574829701562, 'num__clock_speed'),
 (0.028938111743676272, 'num__sc_w'),
 (0.029481277373555843, 'num__pc'),
 (0.031833370368259124, 'num__talk_time'),
 (0.03670476467390924, 'num__int_memory'),
 (0.03877477974707823, 'num__mobile_wt'),
 (0.054979361601635135, 'num__px_height'),
 (0.055448760770609125, 'num__px_width'),
 (0.07060625634336401, 'num__battery_power'),
 (0.4836673528133098, 'num__ram')]

In [ ]:
from sklearn.model_selection import GridSearchCV # RandomizedSearchCV

In [ ]:
param_grid = {
    'estimator__n_estimators': [175, 176, 177, 178, 179]
}

gscv = GridSearchCV(full_pipeline, param_grid, cv=3)
gscv.fit(X_train, y_train)

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('num',
                                                                         Pipeline(steps=[('impute',
                                                                                          SimpleImputer(strategy='median')),
                                                                                         ('scale',
                                                                                          StandardScaler())]),
                                                                         Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi'],
      dtype='object'))])),
                                       ('estimator',
                                        RandomForestClassifier())]),
             param_grid={'estimator__n_estimators': [175, 176, 177, 178, 179]})

In [ ]:
gscv.best_params_

{'estimator__n_estimators': 177}

In [ ]:
gscv.best_estimator_.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi'],
      dtype='object'))])),
                ('estimator', RandomForestClassifier(n_estimators=177))])

In [ ]:
gscv.best_estimator_.score(X_train, y_train), gscv.best_estimator_.score(X_test, y_test)

(1.0, 0.875)

In [ ]:
gscv.best_estimator_.predict(X_test.iloc[:10])

array([0, 0, 1, 0, 2, 1, 0, 2, 2, 3])

In [ ]:
y_test.iloc[:10]

674     0
1699    0
1282    1
1315    1
1210    2
1636    2
613     0
447     2
1131    2
808     3
Name: price_range, dtype: int64

In [ ]:
from sklearn.model_selection import cross_val_score

cross_val_score(full_pipeline, X_train[:1000], y_train[:1000],cv=5, scoring='neg_mean_absolute_error')

array([-0.19 , -0.11 , -0.155, -0.17 , -0.155])

In [ ]:
from  sklearn.ensemble import IsolationForest

In [ ]:
iso_forest=IsolationForest(n_estimators=100,random_state=13)
iso_forest.fit(X_train_prepared)
v = pd.DataFrame(iso_forest.predict(X_train_prepared))
v.value_counts()




0 
-1    1466
 1     134
Name: count, dtype: int64