In [ ]:
import numpy as np
import random

In [ ]:
np.random.seed(1)
random_arr=np.random.randint(1,10,size=(3,2,5,3))
random_arr

array([[[[6, 9, 6],
         [1, 1, 2],
         [8, 7, 3],
         [5, 6, 3],
         [5, 3, 5]],

        [[8, 8, 2],
         [8, 1, 7],
         [8, 7, 2],
         [1, 2, 9],
         [9, 4, 9]]],


       [[[8, 4, 7],
         [6, 2, 4],
         [5, 9, 2],
         [5, 1, 4],
         [3, 1, 5]],

        [[3, 8, 8],
         [9, 7, 4],
         [8, 8, 5],
         [6, 4, 7],
         [9, 1, 3]]],


       [[[8, 8, 8],
         [4, 1, 9],
         [8, 8, 2],
         [2, 4, 1],
         [9, 7, 5]],

        [[6, 7, 3],
         [6, 8, 9],
         [5, 5, 8],
         [8, 5, 1],
         [3, 1, 8]]]])

In [ ]:
np.random.seed(1)
random_arr=np.random.randint(1,10,size=(5,3))
random_arr[:4,2]

array([6, 2, 3, 3])

In [ ]:
np.random.seed(1)
random_arr=np.random.randint(1,10,size=(5,3))
random_arr[:4]

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3],
       [5, 6, 3]])

In [ ]:
np.random.seed(1)
random_arr=np.random.randint(1,10,size=(5,3))
random_arr[:4,1]

array([9, 1, 7, 6])

In [ ]:
np.random.seed(1)
random_arr=np.random.randint(1,10,size=(2,5,5))
random_arr[:,3:,3]


array([[8, 2],
       [1, 9]])

In [ ]:
np.random.seed(1)
random_arr=np.random.randint(1,10,size=(2,5,5))
random_arr[1,1,1:4]

array([4, 7, 6])

In [ ]:
np.random.seed(1)
random_arr=np.random.randint(1,10,size=(2,5,5))
random_arr[1,2,2:]

array([9, 2, 5])

In [ ]:
a2=np.array([[1,2,3],
     [4,5,6]])


In [ ]:
arr_1=np.array([13,15,17])
arr_1

array([13, 15, 17])

In [ ]:
arr_1.ndim

1

In [ ]:
arr_2=np.array([[1,3,5],
               [9,7,5]])
arr_2

array([[1, 3, 5],
       [9, 7, 5]])

In [ ]:
arr_2.ndim

2

In [ ]:
arr_3 = np.array([[[1,2,3],
                  [4,5,6],
                  [7,8,9]]])
arr_3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
arr_3.ndim

3

In [ ]:
arr_1.shape,arr_1.ndim,arr_1.dtype,arr_1.size

((3,), 1, dtype('int64'), 3)

In [ ]:
arr_2.shape,arr_2.ndim,arr_2.dtype,arr_2.size

((2, 3), 2, dtype('int64'), 6)

In [ ]:
arr_3.shape,arr_3.ndim,arr_3.dtype,arr_3.size

((1, 3, 3), 3, dtype('int64'), 9)

In [ ]:
import pandas as pd

In [ ]:
df=pd.DataFrame({'numbers' :[1,2,3,4,5]})
df

numbers
0        1
1        2
2        3
3        4
4        5

In [ ]:
new_arr=np.ones(shape=(10,2),dtype=int)
new_arr

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
new_arr1=np.zeros(shape=(7,2,3),dtype=int)
new_arr1

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [ ]:
arr_l = np.arange(0,100,3)
arr_l

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
import random

In [ ]:
random_arr=np.random.randint(0,10,size=(7,2))
random_arr

array([[9, 3],
       [7, 7],
       [4, 5],
       [9, 3],
       [6, 8],
       [0, 2],
       [7, 7]])

In [ ]:
random_arr1=np.random.rand(3,5)
random_arr1

array([[0.57411761, 0.14672857, 0.58930554, 0.69975836, 0.10233443],
       [0.41405599, 0.69440016, 0.41417927, 0.04995346, 0.53589641],
       [0.66379465, 0.51488911, 0.94459476, 0.58655504, 0.90340192]])

In [ ]:
np.random.seed(42)
random_arr3=np.random.randint(1,10,size=(4,6))
random_arr3

array([[7, 4, 8, 5, 7, 3],
       [7, 8, 5, 4, 8, 8],
       [3, 6, 5, 2, 8, 6],
       [2, 5, 1, 6, 9, 1]])

In [ ]:
np.random.seed(1)
val=np.random.randint(1,10,size=(3,7))
val

array([[6, 9, 6, 1, 1, 2, 8],
       [7, 3, 5, 6, 3, 5, 3],
       [5, 8, 8, 2, 8, 1, 7]])

In [ ]:
np.unique(val)

array([1, 2, 3, 5, 6, 7, 8, 9])

In [ ]:
val[0]

array([6, 9, 6, 1, 1, 2, 8])

In [ ]:
val[:2]

array([[6, 9, 6, 1, 1, 2, 8],
       [7, 3, 5, 6, 3, 5, 3]])

In [ ]:
val[:2,:2]

array([[6, 9],
       [7, 3]])

In [ ]:
np.random.seed(2)
mat=np.random.randint(0,10,size=(3,5))
mat

array([[8, 8, 6, 2, 8],
       [7, 2, 1, 5, 4],
       [4, 5, 7, 3, 6]])

In [ ]:
mat1=np.ones(shape=(3,5),dtype=int)
mat1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
sum=mat+mat1
sum

array([[9, 9, 7, 3, 9],
       [8, 3, 2, 6, 5],
       [5, 6, 8, 4, 7]])

In [ ]:
mat2=np.ones(shape=(5,3),dtype=int)
mat2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
sum2=sum+mat2.T
sum2

array([[10, 10,  8,  4, 10],
       [ 9,  4,  3,  7,  6],
       [ 6,  7,  9,  5,  8]])

In [ ]:
ones_val=np.ones(shape=(3,5),dtype=int)
ones_val

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
extract=sum2-ones_val
extract

array([[9, 9, 7, 3, 9],
       [8, 3, 2, 6, 5],
       [5, 6, 8, 4, 7]])

In [ ]:
multiple=extract*ones_val
multiple

array([[9, 9, 7, 3, 9],
       [8, 3, 2, 6, 5],
       [5, 6, 8, 4, 7]])

In [ ]:
p_array=np.power(multiple,2)
p_array

array([[81, 81, 49,  9, 81],
       [64,  9,  4, 36, 25],
       [25, 36, 64, 16, 49]])

In [ ]:
s_array=np.square(p_array)
s_array

array([[6561, 6561, 2401,   81, 6561],
       [4096,   81,   16, 1296,  625],
       [ 625, 1296, 4096,  256, 2401]])

In [ ]:
mean_array=np.mean(s_array)
mean_array

2463.5333333333333

In [ ]:
max_array=np.max(s_array)
max_array

6561

In [ ]:
min_array=np.min(s_array)
min_array

16

In [ ]:
standart_deviation=np.std(s_array)
standart_deviation

2413.9683197773934

In [ ]:
variance_array=np.var(s_array)
variance_array

5827243.048888891

In [ ]:
reshaped_array=s_array.reshape(3,5,1)
reshaped_array

array([[[6561],
        [6561],
        [2401],
        [  81],
        [6561]],

       [[4096],
        [  81],
        [  16],
        [1296],
        [ 625]],

       [[ 625],
        [1296],
        [4096],
        [ 256],
        [2401]]])

In [ ]:
transpose_array=s_array.T
transpose_array

array([[6561, 4096,  625],
       [6561,   81, 1296],
       [2401,   16, 4096],
       [  81, 1296,  256],
       [6561,  625, 2401]])

In [ ]:
np.random.seed(31)
val1=np.random.randint(0,10,size=(3,3))
val1

array([[2, 7, 0],
       [2, 7, 6],
       [6, 2, 2]])

In [ ]:
np.random.seed(13)
val2=np.random.randint(0,10,size=(3,2))
val2

array([[2, 0],
       [0, 6],
       [2, 4]])

In [ ]:
dot_value=np.dot(val1,val2)
dot_value

array([[ 4, 42],
       [16, 66],
       [16, 20]])

In [ ]:
np.random.seed(5)
Mat1=np.random.randint(0,10,size=(4,3))
Mat1

array([[3, 6, 6],
       [0, 9, 8],
       [4, 7, 0],
       [0, 7, 1]])

In [ ]:
np.random.seed(4)
Mat2=np.random.randint(0,10,size=(4,3))
Mat2

array([[7, 5, 1],
       [8, 7, 8],
       [2, 9, 7],
       [7, 7, 9]])

In [ ]:
dot_value2=np.dot(Mat1,Mat2.T)
dot_value2

array([[ 57, 114, 102, 117],
       [ 53, 127, 137, 135],
       [ 63,  81,  71,  77],
       [ 36,  57,  70,  58]])

In [ ]:
np.random.seed(100)
A= np.random.randint(0,10,size=(3,5))
A

array([[8, 8, 3, 7, 7],
       [0, 4, 2, 5, 2],
       [2, 2, 1, 0, 8]])

In [ ]:
np.random.seed(101)
B= np.random.randint(0,10,size=(3,5))
B

array([[1, 6, 7, 9, 8],
       [4, 8, 5, 0, 5],
       [8, 1, 3, 8, 3]])

In [ ]:
A>=B

array([[ True,  True, False, False, False],
       [False, False, False,  True, False],
       [False,  True, False, False,  True]])

In [ ]:
A>7

array([[ True,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True]])

In [ ]:
A==B

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [ ]:
np.sort(B)

array([[1, 6, 7, 8, 9],
       [0, 4, 5, 5, 8],
       [1, 3, 3, 8, 8]])

In [ ]:
np.argmax(B)

3

In [ ]:
import pandas as pd

data = [[3, 108939], [2, 12747], [8, 87709], [6, 91796]]
accounts = pd.DataFrame(data, columns=['account_id', 'income']).astype({'account_id':'Int64', 'income':'Int64'})

In [ ]:
categories = pd.DataFrame({'category': ['High Salary', 'Low Salary', 'Average Salary']})
accounts['category']=accounts['income'].map(lambda x: 'Low Salary' if x < 20000 else ('Average Salary' if  20000 < x <50000 else 'High Salary'))
accounts = pd.merge(categories, accounts, on = 'category', how = 'left')
accounts.groupby('category').count().reset_index()[['category',	'account_id']].rename(columns = {'account_id': "accounts_count"})
# accounts.groupby('category').size().to_frame('accounts_count').reset_index()


category  accounts_count
0  Average Salary               0
1     High Salary               3
2      Low Salary               1

In [ ]:
accounts

category  account_id  income
0     High Salary           3  108939
1     High Salary           8   87709
2     High Salary           6   91796
3     High Salary        <NA>    <NA>
4      Low Salary           2   12747
5  Average Salary        <NA>    <NA>

In [ ]:
data = [[8], [8], [3], [3], [1], [4], [5], [6]]
my_numbers = pd.DataFrame(data, columns=['num']).astype({'num':'Int64'})
my_numbers


num
0    8
1    8
2    3
3    3
4    1
5    4
6    5
7    6

In [ ]:
df= my_numbers.value_counts().reset_index()
df1= df[df['count']==1]
a= df1[df1['num']==df1['num'].max()][['num']]
a

num
5    6

In [ ]:
df1.map(lambda x : 'none' if len(df1) == 0 else  a)

num          count
2     num
5    6     num
5    6
3     num
5    6     num
5    6
4     num
5    6     num
5    6
5     num
5    6     num
5    6

In [ ]:
data = [[1, 'Leetcode Solutions', 'Book'], [2, 'Jewels of Stringology', 'Book'], [3, 'HP', 'Laptop'], [4, 'Lenovo', 'Laptop'], [5, 'Leetcode Kit', 'T-shirt']]
products = pd.DataFrame(data, columns=['product_id', 'product_name', 'product_category']).astype({'product_id':'Int64', 'product_name':'object', 'product_category':'object'})
data = [[1, '2020-02-05', 60], [1, '2020-02-10', 70], [2, '2020-01-18', 30], [2, '2020-02-11', 80], [3, '2020-02-17', 2], [3, '2020-02-24', 3], [4, '2020-03-01', 20], [4, '2020-03-04', 30], [4, '2020-03-04', 60], [5, '2020-02-25', 50], [5, '2020-02-27', 50], [5, '2020-03-01', 50]]
orders = pd.DataFrame(data, columns=['product_id', 'order_date', 'unit']).astype({'product_id':'Int64', 'order_date':'datetime64[ns]', 'unit':'Int64'})
orders

product_id order_date  unit
0            1 2020-02-05    60
1            1 2020-02-10    70
2            2 2020-01-18    30
3            2 2020-02-11    80
4            3 2020-02-17     2
5            3 2020-02-24     3
6            4 2020-03-01    20
7            4 2020-03-04    30
8            4 2020-03-04    60
9            5 2020-02-25    50
10           5 2020-02-27    50
11           5 2020-03-01    50

In [ ]:
products

product_id           product_name product_category
0           1     Leetcode Solutions             Book
1           2  Jewels of Stringology             Book
2           3                     HP           Laptop
3           4                 Lenovo           Laptop
4           5           Leetcode Kit          T-shirt

In [ ]:
df1=orders[(pd.to_datetime(orders['order_date']).dt.month.reset_index()==2) & (pd.to_datetime(orders['order_date']).dt.year.reset_index()==2020)].dropna(subset='order_date')[['order_date']]
df1

order_date
0  2020-02-05
1  2020-02-10
3  2020-02-11
4  2020-02-17
5  2020-02-24
9  2020-02-25
10 2020-02-27

In [ ]:
orders = orders[(orders['order_date'].dt.month == 2) & (orders['order_date'].dt.year == 2020)].groupby(['product_id'])['unit'].sum().reset_index()
orders

product_id  unit
0           1   130
1           2    80
2           3     5
3           5   100

In [ ]:
orders = orders[orders['unit'] >= 100]
pd.merge(products, orders, on = 'product_id')[['product_name', 'unit']]

product_name  unit
0  Leetcode Solutions   130
1        Leetcode Kit   100

In [ ]:
val=orders.merge(df1,on='order_date',how='right')
val

product_id order_date  unit
0           1 2020-02-05    60
1           1 2020-02-10    70
2           2 2020-02-11    80
3           3 2020-02-17     2
4           3 2020-02-24     3
5           5 2020-02-25    50
6           5 2020-02-27    50

In [ ]:
val1=val.groupby('product_id').sum('unit').reset_index()
val1=val1[val1['unit']>=100]
val1

product_id  unit
0           1   130
3           5   100

In [ ]:
products.merge(val1,on='product_id')[['product_name','unit']]

product_name  unit
0  Leetcode Solutions   130
1        Leetcode Kit   100